package com.ringoid.base.manager

object Analytics {
    const val SCREEN_SIGN_UP = "SCREEN_SIGN_UP"
    const val AUTH_USER_PROFILE_CREATED = "AUTH_USER_PROFILE_CREATED"
    const val AUTH_USER_CALL_DELETE_HIMSELF = "AUTH_USER_CALL_DELETE_HIMSELF"
    const val ACTION_USER_LIKE_PHOTO = "ACTION_USER_LIKE_PHOTO"
    const val ACTION_USER_BLOCK_OTHER = "ACTION_USER_BLOCK_OTHER"
    const val ACTION_USER_UNLIKE_PHOTO = "ACTION_USER_UNLIKE_PHOTO"
    const val ACTION_USER_MESSAGE = "ACTION_USER_MESSAGE"
    const val IMAGE_USER_UPLOAD_PHOTO = "IMAGE_USER_UPLOAD_PHOTO"
    const val IMAGE_USER_DELETE_PHOTO = "IMAGE_USER_DELETE_PHOTO"
}
