package com.ringoid.origin.feed.adapter.base

sealed class FeedViewHolderPayload

object FeedViewHolderHideControls : FeedViewHolderPayload()
object FeedViewHolderShowControls : FeedViewHolderPayload()
object FeedFooterViewHolderHideControls : FeedViewHolderPayload()
object FeedFooterViewHolderShowControls : FeedViewHolderPayload()

object FeedViewHolderHideAgeOnScroll : FeedViewHolderPayload()
object FeedViewHolderShowAgeOnScroll : FeedViewHolderPayload()
object FeedViewHolderHideChatBtnOnScroll : FeedViewHolderPayload()
object FeedViewHolderShowChatBtnOnScroll : FeedViewHolderPayload()
object FeedViewHolderHideDistanceOnScroll : FeedViewHolderPayload()
object FeedViewHolderShowDistanceOnScroll : FeedViewHolderPayload()
object FeedViewHolderHideEducationOnScroll : FeedViewHolderPayload()
object FeedViewHolderShowEducationOnScroll : FeedViewHolderPayload()
object FeedViewHolderHideHairColorOnScroll : FeedViewHolderPayload()
object FeedViewHolderShowHairColorOnScroll : FeedViewHolderPayload()
object FeedViewHolderHideHeightOnScroll : FeedViewHolderPayload()
object FeedViewHolderShowHeightOnScroll : FeedViewHolderPayload()
object FeedViewHolderHideIncomeOnScroll : FeedViewHolderPayload()
object FeedViewHolderShowIncomeOnScroll : FeedViewHolderPayload()
object FeedViewHolderHideOnlineStatusOnScroll : FeedViewHolderPayload()
object FeedViewHolderShowOnlineStatusOnScroll : FeedViewHolderPayload()
object FeedViewHolderHidePropertyOnScroll : FeedViewHolderPayload()
object FeedViewHolderShowPropertyOnScroll : FeedViewHolderPayload()
object FeedViewHolderHideSettingsBtnOnScroll : FeedViewHolderPayload()
object FeedViewHolderShowSettingsBtnOnScroll : FeedViewHolderPayload()
object FeedViewHolderShowTabsIndicatorOnScroll : FeedViewHolderPayload()
object FeedViewHolderHideTabsIndicatorOnScroll : FeedViewHolderPayload()
object FeedViewHolderHideTransportOnScroll : FeedViewHolderPayload()
object FeedViewHolderShowTransportOnScroll : FeedViewHolderPayload()
